-- AlterTable
ALTER TABLE `Ship` ADD COLUMN `behaviorOnce` BOOLEAN NULL,
    MODIFY `currentBehavior` ENUM('TRADE', 'UPDATE_MARKETS', 'EXPLORE_MARKETS', 'EXPLORE', 'MAP_JUMPGATE', 'MINE', 'TRAVEL') NULL;
