/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A cooldown is a period of time in which a ship cannot perform certain actions.
 * @export
 * @interface Cooldown
 */
export interface Cooldown {
    /**
     * The symbol of the ship that is on cooldown
     * @type {string}
     * @memberof Cooldown
     */
    'shipSymbol': string;
    /**
     * The total duration of the cooldown in seconds
     * @type {number}
     * @memberof Cooldown
     */
    'totalSeconds': number;
    /**
     * The remaining duration of the cooldown in seconds
     * @type {number}
     * @memberof Cooldown
     */
    'remainingSeconds': number;
    /**
     * The date and time when the cooldown expires in ISO 8601 format
     * @type {string}
     * @memberof Cooldown
     */
    'expiration': string;
}

