/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MarketTradeGood
 */
export interface MarketTradeGood {
    /**
     * The symbol of the trade good.
     * @type {string}
     * @memberof MarketTradeGood
     */
    'symbol': string;
    /**
     * The typical volume flowing through the market for this type of good. The larger the trade volume, the more stable prices will be.
     * @type {number}
     * @memberof MarketTradeGood
     */
    'tradeVolume': number;
    /**
     * A rough estimate of the total supply of this good in the marketplace.
     * @type {string}
     * @memberof MarketTradeGood
     */
    'supply': MarketTradeGoodSupplyEnum;
    /**
     * The price at which this good can be purchased from the market.
     * @type {number}
     * @memberof MarketTradeGood
     */
    'purchasePrice': number;
    /**
     * The price at which this good can be sold to the market.
     * @type {number}
     * @memberof MarketTradeGood
     */
    'sellPrice': number;
}

export const MarketTradeGoodSupplyEnum = {
    Scarce: 'SCARCE',
    Limited: 'LIMITED',
    Moderate: 'MODERATE',
    Abundant: 'ABUNDANT'
} as const;

export type MarketTradeGoodSupplyEnum = typeof MarketTradeGoodSupplyEnum[keyof typeof MarketTradeGoodSupplyEnum];


