/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ShipRequirements } from './ship-requirements';

/**
 * The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
 * @export
 * @interface ShipFrame
 */
export interface ShipFrame {
    /**
     * 
     * @type {string}
     * @memberof ShipFrame
     */
    'symbol': ShipFrameSymbolEnum;
    /**
     * 
     * @type {string}
     * @memberof ShipFrame
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ShipFrame
     */
    'description': string;
    /**
     * Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.
     * @type {number}
     * @memberof ShipFrame
     */
    'condition'?: number;
    /**
     * 
     * @type {number}
     * @memberof ShipFrame
     */
    'moduleSlots': number;
    /**
     * 
     * @type {number}
     * @memberof ShipFrame
     */
    'mountingPoints': number;
    /**
     * 
     * @type {number}
     * @memberof ShipFrame
     */
    'fuelCapacity': number;
    /**
     * 
     * @type {ShipRequirements}
     * @memberof ShipFrame
     */
    'requirements': ShipRequirements;
}

export const ShipFrameSymbolEnum = {
    Probe: 'FRAME_PROBE',
    Drone: 'FRAME_DRONE',
    Interceptor: 'FRAME_INTERCEPTOR',
    Racer: 'FRAME_RACER',
    Fighter: 'FRAME_FIGHTER',
    Frigate: 'FRAME_FRIGATE',
    Shuttle: 'FRAME_SHUTTLE',
    Explorer: 'FRAME_EXPLORER',
    Miner: 'FRAME_MINER',
    LightFreighter: 'FRAME_LIGHT_FREIGHTER',
    HeavyFreighter: 'FRAME_HEAVY_FREIGHTER',
    Transport: 'FRAME_TRANSPORT',
    Destroyer: 'FRAME_DESTROYER',
    Cruiser: 'FRAME_CRUISER',
    Carrier: 'FRAME_CARRIER'
} as const;

export type ShipFrameSymbolEnum = typeof ShipFrameSymbolEnum[keyof typeof ShipFrameSymbolEnum];


