/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetFaction200Response } from '../models';
// @ts-ignore
import { GetFactions200Response } from '../models';
/**
 * FactionsApi - axios parameter creator
 * @export
 */
export const FactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * View the details of a faction.
         * @summary Get Faction
         * @param {string} factionSymbol The faction symbol
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFaction: async (factionSymbol: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'factionSymbol' is not null or undefined
            assertParamExists('getFaction', 'factionSymbol', factionSymbol)
            const localVarPath = `/factions/{factionSymbol}`
                .replace(`{${"factionSymbol"}}`, encodeURIComponent(String(factionSymbol)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AgentToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all discovered factions in the game.
         * @summary List Factions
         * @param {number} [page] What entry offset to request
         * @param {number} [limit] How many entries to return per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFactions: async (page?: number, limit?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/factions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AgentToken required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FactionsApi - functional programming interface
 * @export
 */
export const FactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * View the details of a faction.
         * @summary Get Faction
         * @param {string} factionSymbol The faction symbol
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFaction(factionSymbol: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFaction200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFaction(factionSymbol, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * List all discovered factions in the game.
         * @summary List Factions
         * @param {number} [page] What entry offset to request
         * @param {number} [limit] How many entries to return per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFactions(page?: number, limit?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFactions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFactions(page, limit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FactionsApi - factory interface
 * @export
 */
export const FactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FactionsApiFp(configuration)
    return {
        /**
         * View the details of a faction.
         * @summary Get Faction
         * @param {string} factionSymbol The faction symbol
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFaction(factionSymbol: string, options?: any): AxiosPromise<GetFaction200Response> {
            return localVarFp.getFaction(factionSymbol, options).then((request) => request(axios, basePath));
        },
        /**
         * List all discovered factions in the game.
         * @summary List Factions
         * @param {number} [page] What entry offset to request
         * @param {number} [limit] How many entries to return per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFactions(page?: number, limit?: number, options?: any): AxiosPromise<GetFactions200Response> {
            return localVarFp.getFactions(page, limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FactionsApi - object-oriented interface
 * @export
 * @class FactionsApi
 * @extends {BaseAPI}
 */
export class FactionsApi extends BaseAPI {
    /**
     * View the details of a faction.
     * @summary Get Faction
     * @param {string} factionSymbol The faction symbol
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FactionsApi
     */
    public getFaction(factionSymbol: string, options?: AxiosRequestConfig) {
        return FactionsApiFp(this.configuration).getFaction(factionSymbol, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all discovered factions in the game.
     * @summary List Factions
     * @param {number} [page] What entry offset to request
     * @param {number} [limit] How many entries to return per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FactionsApi
     */
    public getFactions(page?: number, limit?: number, options?: AxiosRequestConfig) {
        return FactionsApiFp(this.configuration).getFactions(page, limit, options).then((request) => request(this.axios, this.basePath));
    }
}
