[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Bart Riepe <bart@serial-experiments.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ortools = "^9.7.2996"
flask = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
